'use strict';

// tests for createCaseDefinition
// Generated by serverless-mocha-plugin

const mochaPlugin = require( 'serverless-mocha-plugin' );
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper( 'createCaseDefinition', '/handler.js', 'createCaseDefinition' );
const caseDefinitions = require( '../data/case-definitions-with-id.json' );

describe( 'CreateCaseDefinition is importing data', () => {
  before( ( done ) => {
    done();
  } );

  caseDefinitions.forEach( caseDefinition => {
    it( `create case should return id for "${ caseDefinition.name }"`, () => {
      const event = {
        body: JSON.stringify( caseDefinition )
      };
      return wrapped.run( event )
        .then( ( response ) => {
          console.debug( response.body );
          const data = JSON.parse( response.body );
          expect( data.id ).to.be.string;
        } )
        .catch( err => {
          console.error( err );
        } );
    } );
  } );
} );