'use strict';

// tests for createTaskDefinition
// Generated by serverless-mocha-plugin

const mochaPlugin = require( 'serverless-mocha-plugin' );
const expect = mochaPlugin.chai.expect;
const taskDefinitions = require( '../data/task-definitions.json' );

describe( 'createTaskDefinition is importing data', () => {
  before( ( done ) => {
    done();
  } );

  taskDefinitions.forEach( taskDefinition => {
    it( `Create task should return an id for ${ taskDefinition.name }`, () => {
      // const taskDefinition = taskDefinitions[ 0 ];
      const event = {
        body: JSON.stringify( taskDefinition )
      };
      let wrapped = mochaPlugin.getWrapper( 'createTaskDefinition', '/handler.js', 'createTaskDefinition' );
      return wrapped
        .run( event )
        .then( ( response ) => {
          console.debug( response.body );
          const data = JSON.parse( response.body );
          expect( data.id ).to.be.string;
        } )
        .catch( err => {
          console.error( err );
        } );
    } );
  } );
} );