'use strict';

// tests for createCase
// Generated by serverless-mocha-plugin

const mochaPlugin = require( 'serverless-mocha-plugin' );
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper( 'createCase', '/handler.js', 'createCase' );
const caseDefinitions = require( '../data/case-definitions.json' );

describe( 'createCases', () => {
  before( ( done ) => {
    done();
  } );

  it( 'implement tests here', () => {
    caseDefinitions.forEach( caseDefinition => {
      describe( 'createCase', () => {

        const event = {
          body: JSON.stringify( caseDefinition )
        };
        return wrapped.run( event )
          .then( ( response ) => {
            console.log( response.body );
            const data = JSON.parse( response.body );
            expect( data.id ).to.not.be.empty;
            expect( data.id ).to.be.string;
          } )
          .catch( err => {
            console.error( err );
          } );

      } );
    } );
  } );
} );
