// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c17af341-dedc-4a1c-b477-a803382d1d03",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4wy4aRruY",
    "aws_user_pools_web_client_id": "27gli24mmt47t4na4s5pgd27dc",
    "oauth": {
        "domain": "samantha-a71b6c47-a71b6c47-test.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://samantha-test-pocui-079056339674.s3-website-us-east-1.amazonaws.com/",
        "redirectSignOut": "https://samantha-test-pocui-079056339674.s3-website-us-east-1.amazonaws.com/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
