FROM node:12-stretch-slim

RUN apt-get -qy update && apt-get -qy install openssl curl autoconf
RUN npm install -g node-prune
RUN node-prune
# RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

RUN apt-get install -y software-properties-common \
  && add-apt-repository ppa:jonathonf/python-3.8 \
  && apt-get update \
  && apt-get install -y python3.8 \
  && apt-get install -y python3-pip 
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip

RUN mkdir /app
WORKDIR /app

COPY package.json yarn.lock /app/
# COPY ./tests/nightwatch/.env /app/tests/nightwatch/.env
# RUN eval $(cat tests/nightwatch/.env | sed 's/^/export /')
RUN yarn -s install --frozen-lockfile && yarn -s cache clean
RUN /usr/local/bin/node-prune

COPY . /app/

ARG SENTRY_RELEASE="local"
RUN echo "SENTRY_RELEASE=$SENTRY_RELEASE" >> /app/.sentryclirc

RUN yarn build

ENV PATH /app/node_modules/.bin:$PATH

# RUN yarn start:prod
# RUN tests/nightwatch/bin/run.ci.sh

EXPOSE 2000
