FROM node:12-stretch-slim

RUN apt-get -y install apk
RUN apk add build-base python-dev py-pip zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib
RUN apt-get -qy update && apt-get -qy install openssl curl autoconf

RUN npm install -g node-prune
RUN node-prune
# RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

RUN mkdir /app
WORKDIR /app

COPY package.json yarn.lock /app/
# COPY ./tests/nightwatch/.env /app/tests/nightwatch/.env
# RUN eval $(cat tests/nightwatch/.env | sed 's/^/export /')
RUN yarn -s install --frozen-lockfile && yarn -s cache clean
RUN /usr/local/bin/node-prune

COPY . /app/

ARG SENTRY_RELEASE="local"
RUN echo "SENTRY_RELEASE=$SENTRY_RELEASE" >> /app/.sentryclirc

RUN yarn build

ENV PATH /app/node_modules/.bin:$PATH

# RUN yarn start:prod
# RUN tests/nightwatch/bin/run.ci.sh

EXPOSE 2000
