'use strict';

const CONSTANTS = {
    ENVIRONMENT: process.env.ENVIRONMENT,
    COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    BUCKET_NAME: process.env.BUCKET_NAME,
    DYNAMODB_SOCKETS_TABLE: process.env.DYNAMODB_SOCKETS_TABLE,
    DYNAMODB_SOCKETS_USER_GSI: process.env.DYNAMODB_SOCKETS_USER_GSI,
    DYNAMODB_TASKS_TABLE: process.env.DYNAMODB_TASKS_TABLE,
    DYNAMODB_TASKS_USER_GSI: process.env.DYNAMODB_TASKS_USER_GSI,
    DYNAMODB_OPTIONS: {},
    KEYS_URL: process.env.KEYS_URL,
    SIGNED_URL_EXPIRE_SECONDS: 60 * 60,
    WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT
};

module.exports = CONSTANTS;
