// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:361f4b96-5ced-4b13-9bc6-53dbeb7ec36a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vYXPnajjx",
    "aws_user_pools_web_client_id": "6na6p5q6bsksmd4okr8fcqr69j",
    "oauth": {
        "domain": "samantha673e9c6e-673e9c6e-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:2000/",
        "redirectSignOut": "https://localhost:2000/user/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
