INSERT INTO m2.bellhops (id, name, metadata, profile_image_url, created_at, updated_at) VALUES ('6U0uG2uaSVCOgFW_6RU0G', 'Facilities', '{}', NULL, '2020-07-20 21:32:05.280057+00', '2020-07-20 21:32:05.280057+00');
INSERT INTO m2.bellhops (id, name, metadata, profile_image_url, created_at, updated_at) VALUES ('1ibkm0rWaBenw4GvR2_HA', 'Marketing', '{}', NULL, '2020-07-20 21:32:15.007791+00', '2020-07-20 21:32:15.007791+00');
INSERT INTO m2.bellhops (id, name, metadata, profile_image_url, created_at, updated_at) VALUES ('5N7DVIvQIV0dBGx89q9r2', 'Finance', '{}', NULL, '2020-07-20 21:32:24.717504+00', '2020-07-20 21:32:24.717504+00');
INSERT INTO m2.bellhops (id, name, metadata, profile_image_url, created_at, updated_at) VALUES ('rSIbpHk-JU4Rca7sF4Z7A', 'Legal', '{}', NULL, '2020-07-20 21:32:32.292195+00', '2020-07-20 21:32:32.292195+00');
INSERT INTO m2.block_state (state, attribute) VALUES ('Created', NULL);
INSERT INTO m2.block_state (state, attribute) VALUES ('Running', NULL);
INSERT INTO m2.block_state (state, attribute) VALUES ('Success', NULL);
INSERT INTO m2.block_state (state, attribute) VALUES ('Failure', NULL);
INSERT INTO m2.block_state (state, attribute) VALUES ('Draft', NULL);
INSERT INTO m2.block_type (type, category) VALUES ('Sequence', 'Control');
INSERT INTO m2.block_type (type, category) VALUES ('Parallel', 'Control');
INSERT INTO m2.block_type (type, category) VALUES ('FormTask', 'Task');
INSERT INTO m2.block_type (type, category) VALUES ('APIExecutor', 'Executor');
INSERT INTO m2.block_type (type, category) VALUES ('Decorator', 'Decorator');
INSERT INTO m2.block_type (type, category) VALUES ('GoalExecutor', 'Executor');
INSERT INTO m2.block_type (type, category) VALUES ('ConversationalAgent', 'Task');
INSERT INTO m2.membership_roles (role, attribute) VALUES ('admin', NULL);
INSERT INTO m2.membership_roles (role, attribute) VALUES ('approver', NULL);
INSERT INTO m2.membership_roles (role, attribute) VALUES ('member', NULL);
INSERT INTO m2.membership_roles (role, attribute) VALUES ('manager', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('task_assignee', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('bell_initiator', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('bell_owner', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('task_requestor', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('task_follower', NULL);
INSERT INTO m2.participation_roles (role, attribute) VALUES ('bell_follower', NULL);
INSERT INTO m2.users (id, name, email, family_name, given_name, picture) VALUES ('Google_111918078641246610063', 'Baiji He', 'bhe@bellhop.io', 'Baiji', 'He', 'https://lh3.googleusercontent.com/a-/AOh14Ghb68OwaaY2L8jaT0shFyIHT4ZaukDMnyPyUCnY=s96-c');
INSERT INTO m2.users (id, name, email, family_name, given_name, picture) VALUES ('Google_115419186368884878540', 'Tingdong Chen', 'tchen@bellhop.io', 'Chen', 'Tingdong', 'https://lh3.googleusercontent.com/a-/AOh14GiewYead-zagD_r1jSjTcZ4QCoIW9GQoc_Bzb3m=s96-c');
INSERT INTO m2.users (id, name, email, family_name, given_name, picture) VALUES ('Google_109551792009621810100', 'Adam Hiatt', 'ahiatt@bellhop.io', 'Hiatt', 'Adam', 'https://lh6.googleusercontent.com/-c-UyBv5uH2E/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucn0pRn1sP_ehaZlcruXojR5zShqFA/s96-c/photo.jpg');
INSERT INTO m2.users (id, name, email, family_name, given_name, picture) VALUES ('Google_113132363560941198349', 'Ben Werther', 'bwerther@bellhop.io', 'Werther', 'Ben', 'https://lh3.googleusercontent.com/a-/AOh14GiBUMCJtUOa3-tU490ZvIEDVrq93riaTc-iWg9P=s96-c');