import { MutationType } from "../../models/enum"

export default {
  __typename: "Block",
  children: [
    {
      __typename: "Block",
      children: [],
      context: "{}",
      control: "{}",
      description: "Gather Information from Responders",
      name: "Gather Info Form",
      state: "READY",
      type: "Form",
      id: 1,
    },
    {
      __typename: "Block",
      children: [],
      context: "{}",
      control: "{}",
      description: "Ask for Approval",
      name: "Approval Form",
      state: "READY",
      type: "Form",
      id: 1,
    },
    {
      __typename: "Block",
      children: [
        {
          __typename: "Block",
          children: [],
          context: "{}",
          control: "{}",
          description: "Gather Information from Responders",
          name: "Gather Info Form",
          state: "READY",
          type: "Form",
        },
        {
          __typename: "Block",
          children: [],
          context: "{}",
          control: "{}",
          description: "Ask for Approval",
          name: "Approval Form",
          state: "READY",
          type: "Form",
        },
      ],
      context: "{}",
      control: "{}",
      description: "Status Update which gathers information and gets approval",
      id: "7f24b1d7-2b31-4aaa-8d2c-3fda6af2f8a4",
      name: "Status Update Request Sequential",
      parent: null,
      requestors: [],
      responders: [],
      state: "READY",
      type: "Sequence",
      __mutation_type__: MutationType.Create,
    },
  ],
  context: "{}",
  control: "{}",
  description: "Status Update which gathers information and gets approval",
  name: "",
  parent: null,
  requestors: ["baiji"],
  responders: ["jin", "tingdong"],
  id: 1,
  state: "READY",
  type: "ParallelAll",
}
