import { MutationType } from "../../models/enum"

export default {
  __mutation_type__: MutationType.Create,
  __typename: "BlockDef",
  children: [
    {
      __typename: "BlockDef",
      children: [
        {
          __typename: "BlockDef",
          children: [],
          context: "{}",
          control: "{}",
          description: "Gather Information from Responders",
          id: "3e423d1a-5f2e-42e9-8fc8-6cd8ab2bd79f",
          name: "Gather Info Form",
          type: "Form",
        },
        {
          __typename: "BlockDef",
          children: [],
          context: "{}",
          control: "{}",
          description: "Ask for Approval",
          id: "e85768eb-a22c-498e-a8ca-c779e3917096",
          name: "Approval Form",
          type: "Form",
        },
      ],
      context: "{}",
      control: "{}",
      description: "Status Update which gathers information and gets approval",
      id: "9a8f9525-435c-4c7c-9c74-ce8206864dea",
      name: "Status Update Request",
      type: "Sequence",
    },
    {
      __typename: "BlockDef",
      children: [],
      context: "{}",
      control: "{}",
      description: "Ask for Approval",
      id: "6bd56afe-9c50-4084-a154-fe40fe867750",
      name: "Approval Form",
      type: "Form",
    },
  ],
  context: "{}",
  control: "{}",
  description: "Status Update which gathers information and gets approval",
  id: "29de52c6-310f-4c8d-bde6-efe46bc25620",
  name: "test",
  parent: null,
  requestors: ["Google_111918078641246610063"],
  responders: ["Google_111918078641246610063"],
  state: "READY",
  type: "ParallelAll",
}
