FROM node:12-stretch-slim

RUN apt update && apt install -y git apt-utils
RUN git config --global http.sslverify false

RUN mkdir /app
WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn -s install --frozen-lockfile && yarn -s cache clean
RUN npx browserslist --update-db
COPY . /app/

ARG SENTRY_RELEASE="local"
RUN echo "SENTRY_RELEASE=$SENTRY_RELEASE" >> /app/.sentryclirc

RUN yarn build

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3030