INSERT INTO public."BlockState" (value, comment) VALUES ('Created', NULL);
INSERT INTO public."BlockState" (value, comment) VALUES ('Ready', NULL);
INSERT INTO public."BlockState" (value, comment) VALUES ('Running', NULL);
INSERT INTO public."BlockState" (value, comment) VALUES ('Success', NULL);
INSERT INTO public."BlockState" (value, comment) VALUES ('Failure', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('API', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('BlackboardCondition', 'The Blackboard node will check to see if a value is set on the given Blackboard Key.');
INSERT INTO public."BlockType" (value, comment) VALUES ('Selector', 'Selector Nodes execute their children from left to right. They stop executing when one of their children succeeds. If a Selector''s child succeeds, the Selector succeeds. If all the Selector''s children fail, the Selector fails.');
INSERT INTO public."BlockType" (value, comment) VALUES ('Sequence', 'Sequence nodes execute their children from left to right. They stop executing when one of their children fails. If a child fails, then the Sequence fails. If all the Sequence''s children succeed, then the Sequence succeeds.');
INSERT INTO public."BlockType" (value, comment) VALUES ('ParallelAll', 'ParallelAll nodes execute all their children at the same time. If a child fails, then the ParallelAll fails. If all the Sequence''s children succeed, then the ParallelAll succeeds.');
INSERT INTO public."BlockType" (value, comment) VALUES ('HumanForm', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('ParallelAny', 'ParallelAny nodes execute all their children at the same time. If a ParallelAny''s child succeeds, the ParallelAny succeeds. If all the ParallelAny''s children fail, the ParallelAny fails.');
INSERT INTO public."BlockType" (value, comment) VALUES ('ManualSelector', 'ManualSelector Nodes allow human to choose which children to execute. If any selected child fails, then the ManualSelector fails. If all the ManualSelector''s selected children succeed, then the ManualSelector succeeds.');
INSERT INTO public."BlockType" (value, comment) VALUES ('FinishWithResult', 'The Finish With Result Task node can be used to instantly finish with a given result. This node can be used to force a branch to exit or continue based on the defined result.');
INSERT INTO public."BlockType" (value, comment) VALUES ('BehaviorTree', 'The root node.');
INSERT INTO public."BlockType" (value, comment) VALUES ('SubTree', 'Run a BehaviorTree');
INSERT INTO public."BlockType" (value, comment) VALUES ('Timeout', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('Loop', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('Conditional', NULL);
INSERT INTO public."BlockType" (value, comment) VALUES ('Inverter', NULL);
INSERT INTO public."BlockDefState" (value, comment) VALUES ('Draft', NULL);
INSERT INTO public."BlockDefState" (value, comment) VALUES ('Published', NULL);
