AWSTemplateFormatVersion: "2010-09-09"
Outputs:
  DeploymentHistoryTag:
    Description: Stackery Deployment History Tag
    Value: 4TC9MA
Parameters:
  DeploymentTimestamp:
    Default: "1578707565951"
    Description: Deployment preparation timestamp in milliseconds Since Epoch (injected
      by Stackery at deployment time)
    Type: Number
  EnvironmentTagName:
    Default: ctd
    Description: Environment Name (injected by Stackery at deployment time)
    Type: String
  StackTagName:
    Default: samantha
    Description: Stack Name (injected by Stackery at deployment time)
    Type: String
Resources:
  DeployPocUI:
    DependsOn: DeploymentMarkerTag4TC9MA
    Properties:
      CodeUri: ./
      Description:
        Fn::Sub:
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: DeployPocUI
      Environment:
        Variables:
          BUCKET_ARN:
            Fn::GetAtt:
            - PocUI
            - Arn
          BUCKET_NAME:
            Ref: PocUI
      FunctionName:
        Fn::Sub: ${AWS::StackName}-DeployPocUI
      Handler: index.handler
      MemorySize: 3008
      Policies:
      - AWSXrayWriteOnlyAccess
      - S3CrudPolicy:
          BucketName:
            Ref: PocUI
      Runtime: nodejs12.x
      Timeout: 30
      Tracing: Active
    Type: AWS::Serverless::Function
  DeployPocUIDeployTrigger:
    DependsOn: DeploymentMarkerTag4TC9MA
    Properties:
      DeploymentTimestamp:
        Ref: DeploymentTimestamp
      ServiceToken:
        Fn::GetAtt:
        - DeployPocUI
        - Arn
    Type: Custom::FunctionDeployTrigger
  DeploymentMarkerTag4TC9MA:
    Type: AWS::CloudFormation::WaitConditionHandle
  PocUI:
    DependsOn: DeploymentMarkerTag4TC9MA
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-pocui-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
